// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFNZpryGeCNSEzedKFJNvq5U_kSulbrQc',
    appId: '1:896120528018:android:bade9fb1c451d3f4c79a4b',
    messagingSenderId: '896120528018',
    projectId: 'cookpad-clone',
    storageBucket: 'cookpad-clone.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAES40j0tfQdcjUM4A83zp-UOukvP6C7LU',
    appId: '1:896120528018:web:6bd5c4eec594bd50c79a4b',
    messagingSenderId: '896120528018',
    projectId: 'cookpad-clone',
    authDomain: 'cookpad-clone.firebaseapp.com',
    storageBucket: 'cookpad-clone.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAES40j0tfQdcjUM4A83zp-UOukvP6C7LU',
    appId: '1:896120528018:web:05dafcc36eb1c67ec79a4b',
    messagingSenderId: '896120528018',
    projectId: 'cookpad-clone',
    authDomain: 'cookpad-clone.firebaseapp.com',
    storageBucket: 'cookpad-clone.firebasestorage.app',
  );

}